const SET_LOGGEDIN_USER = 'SET_LOGGEDIN_USER';
const LOGOUT = 'LOGOUT';
const LOGIN = 'LOGIN';
const FETCH_SINGLE_SUCCESS = 'FETCH_SINGLE_SUCCESS';
const FETCH_PRODUCTS_ERROR = 'FETCH_PRODUCTS_ERROR';
const REMOVE_FAV = 'REMOVE_FAV';
const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
const ADD_FAVORITE = 'ADD_FAVORITE';
const FETCH_SINGLE_PENDING = 'FETCH_SINGLE_PENDING';
const LOGIN_USER_PENDING = 'LOGIN_USER_PENDING';
const FETCH_PRODUCTS_PENDING = 'FETCH_PRODUCTS_PENDING';
const CREATE_ITEM_PENDING = 'CREATE_ITEM_PENDING';

export {
  FETCH_PRODUCTS_ERROR,
  FETCH_PRODUCTS_PENDING,
  FETCH_SINGLE_SUCCESS,
  FETCH_PRODUCTS_SUCCESS,
  SET_LOGGEDIN_USER,
  CREATE_ITEM_PENDING,
  REMOVE_FAV,
  ADD_FAVORITE,
  LOGIN,
  LOGOUT,
  FETCH_SINGLE_PENDING,
  LOGIN_USER_PENDING,
};
